### ISSUE TITLE
please provide json usage

### ISSUE THREAD

**Issue by rfyiamcool** [youzan/ZanRedisDB#6]
please provide some json usage, thank u !

**Comment by absolute8511** [comment]
pls see here: http://youzan-zanredisdb.readthedocs.io/en/latest/user-guide/ , all command can be used with the go-sdk. https://godoc.org/github.com/youzan/go-zanredisdb#ZanRedisClient.DoRedis

**Comment by rfyiamcool** [comment]
thank you @absolute8511
